Sentraliser miljøvariabler (del 3)
navikt/fritakagp pull request #235
Opened 2022-12-14 13:29 UTC by bjerga

Fjerner lesing av miljøvariabler som ikke finnes. Lesingen ble lagt til i første forsøk av en autentiseringskonfig i https://github.com/navikt/fritakagp/commit/8d040a3a7823750ad422267f584e3bb443e7073d og fjernet i https://github.com/navikt/fritakagp/commit/3191df96719c982c31e486c41b0861831b9b14a3. Det er noen av miljøvariablene som aldri har eksistert.

2023-06-14 08:26 UTC, b162214 requested changes

2023-06-14 08:26 UTC, b162214 commented on src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
> +        OAuth2TokenProvider(accessTokenService, clientConfig)
blir ikke dette feil?
er nye clientConfig det samme som clientConfig.azureAdConfig() ?

2023-06-14 08:35 UTC, alpet commented on src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
> +        OAuth2TokenProvider(accessTokenService, clientConfig)
> blir ikke dette feil? er nye clientConfig det samme som clientConfig.azureAdConfig() ?

Jeg har ikke gått gjennom koden, men den er også ikke eksplisit. Og sånne type konfigurasjon man vil ha det Veldig eksplisit. Det er ikke nødvendigvis de som forvalter modulen som er interresert i dette konfigurasjon.

2023-06-14 08:40 UTC, alpet commented on src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
> +        OAuth2TokenProvider(accessTokenService, clientConfig)
Ja, nå leste jeg koden. Jeg anbefaler at man blir så eksplisitt som mulig har.

2023-06-14 10:17 UTC, bjerga commented on src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
> +        OAuth2TokenProvider(accessTokenService, clientConfig)
@b162214 `clientConfig` blir det samme som `clientConfig.azureAdConfig()`, ja.

@alpet Tenker du det er tilstrekkelig om man omdøper `clientConfig` til `azureAdConfig`?

2023-06-14 10:19 UTC, alpet commented on src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
> +        OAuth2TokenProvider(accessTokenService, clientConfig)
Ja, det er nok.

2023-06-14 12:57 UTC, bjerga commented on src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt
> +        OAuth2TokenProvider(accessTokenService, clientConfig)
Bedre nå?

2023-06-15 07:27 UTC, b162214 approved these changes

2023-06-15 11:32 UTC, merged