Fas ut bruken av vår egen proxy for å snakke med pdl
navikt/fritakagp pull request #299
Opened 2024-05-16 08:19 UTC by magnusae

Etter denne (https://github.com/navikt/pdl/commit/b0d860a10b88bbfea7c66fa29d1a8775e647a051) endringen i PDL, så skal vi nå kunne slutte å bruke vår egen proxy for å kommunisere med PDL i prod.

2024-05-16 08:48 UTC, b162214 approved these changes

2024-05-16 08:50 UTC, b162214 requested changes
Obs. Man må kanskje bruke pdl scope også?

2024-05-16 08:54 UTC, magnusae commented
> Obs. Man må kanskje bruke pdl scope også?

Ja, bra du er på! 😄 Satt akkurat og så på det med @bjerga nå

2024-05-16 08:57 UTC, bjerga requested changes
PDL_SCOPE må tas i bruk. Du kan kopiere fremgangsmåten til andre scope i følgende filer:
https://github.com/navikt/fritakagp/blob/7bfb147c43bced1f4e3fd85a4a23fb02c8f14d20/src/main/resources/application.conf#L113
https://github.com/navikt/fritakagp/blob/7bfb147c43bced1f4e3fd85a4a23fb02c8f14d20/src/main/kotlin/no/nav/helse/fritakagp/Env.kt#L90
https://github.com/navikt/fritakagp/blob/7bfb147c43bced1f4e3fd85a4a23fb02c8f14d20/src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt#L81-L93

... og deretter bruker scopet i https://github.com/navikt/fritakagp/blob/7bfb147c43bced1f4e3fd85a4a23fb02c8f14d20/src/main/kotlin/no/nav/helse/fritakagp/koin/ExternalSystemsModule.kt#L81-L93.

2024-05-21 08:57 UTC, b162214 approved these changes

2024-05-21 10:20 UTC, merged