lagt til validering til gravid request
navikt/fritakagp pull request #3
Opened 2020-11-19 14:39 UTC by ehsansadeghi-inno

2020-11-19 15:11 UTC, MajaHelene requested changes
Veldig bra👍

2020-11-19 15:11 UTC, MajaHelene commented on src/main/kotlin/no/nav/helse/fritakagp/web/api/resreq/GravidResReq.kt
> +            validate(GravideSoknadRequest::omplassering).isInIgnoringCase("Ja","Nei", "Ikke_mulig")
Kunne kanskje brukt `Omplassering.values().map{it.name}` i stedet for å hardkode ja/nei/ikke_mulig på nytt her 🤷‍♀️

2020-11-19 15:22 UTC, MajaHelene approved these changes
👏 👏

2020-11-20 08:44 UTC, tuxbear approved these changes

2020-11-20 09:49 UTC, merged